name: Jacoco

on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Build with Maven
        run: mvn test jacoco:report verify -e -X
      - name: Upload Jacoco to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-code-coverage
          path: target/site/jacoco/**/*
